/*
 * JumpCloud APIs
 *
 *  JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1

type Mdm struct {
	CreatedAt string `json:"createdAt,omitempty"`

	Dep bool `json:"dep,omitempty"`

	EnrollmentType string `json:"enrollmentType,omitempty"`

	IsSupervised bool `json:"isSupervised,omitempty"`

	ProfileIdentifier string `json:"profileIdentifier,omitempty"`

	UpdatedAt string `json:"updatedAt,omitempty"`

	UserApproved bool `json:"userApproved,omitempty"`

	Vendor string `json:"vendor,omitempty"`
}
