/*
 * JumpCloud APIs
 *
 *  JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1

type UserMetric struct {
	Admin bool `json:"admin,omitempty"`

	CollectionTime string `json:"collectionTime,omitempty"`

	CreationTime string `json:"creationTime,omitempty"`

	IsFDEUser bool `json:"isFDEUser,omitempty"`

	LastLogin string `json:"lastLogin,omitempty"`

	LastPasswordChange string `json:"lastPasswordChange,omitempty"`

	Managed bool `json:"managed,omitempty"`

	SecureTokenEnabled bool `json:"secureTokenEnabled,omitempty"`

	SecureTokenPwEnteredTime string `json:"secureTokenPwEnteredTime,omitempty"`

	Suspended bool `json:"suspended,omitempty"`

	UserName string `json:"userName,omitempty"`

	UserNameHash string `json:"userNameHash,omitempty"`
}
