/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsLinuxPackages struct {
	Arch string `json:"arch,omitempty"`

	CollectionTime string `json:"collection_time,omitempty"`

	InstallTime int32 `json:"install_time,omitempty"`

	MaintainerOrVendor string `json:"maintainer_or_vendor,omitempty"`

	MountNamespaceId string `json:"mount_namespace_id,omitempty"`

	Name string `json:"name,omitempty"`

	PackageFormat string `json:"package_format,omitempty"`

	PackageGroupOrSection string `json:"package_group_or_section,omitempty"`

	PidWithNamespace int32 `json:"pid_with_namespace,omitempty"`

	ReleaseOrRevision string `json:"release_or_revision,omitempty"`

	Size string `json:"size,omitempty"`

	SystemId string `json:"system_id,omitempty"`

	Version string `json:"version,omitempty"`
}
